### ISSUE TITLE
Это валидатор? если да, то можно сделать 1 валидатор для всех значений и вызывать его методы.

### ISSUE THREAD

**Issue by tgurskaya96** [rin-amari/java-labs#2]
https://github.com/rin-amari/java-labs/blob/612e71270578fc6348a56b3e947f25145d169938/src/main/java/com/bsuir/lr/demo/controllers/DryMassController.java#L50

**Comment by rin-amari** [comment]
Да, исправила. Теперь вызываются методы валидатора
