### ISSUE TITLE
Зачем нужны все предыдущие действия? почему в результате будет всегда ok, 0 и это не зависит от предыдущих действий?

### ISSUE THREAD

**Issue by tgurskaya96** [rin-amari/java-labs#7]
https://github.com/rin-amari/java-labs/blob/612e71270578fc6348a56b3e947f25145d169938/src/main/java/com/bsuir/lr/demo/controllers/DryMassController.java#L106

**Comment by rin-amari** [comment]
Исправила, теперь возвращает "Error", -1 при вылете exeption, убрала цикл из Issue 6
